org.gradle.jvmargs=-Xmx4096m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=4
systemProp.http.socketTimeout=120000
systemProp.http.connectionTimeout=120000
systemProp.https.socketTimeout=120000
systemProp.https.connectionTimeout=120000
systemProp.javax.net.debug=ssl:handshake
org.gradle.internal.network.ssl.checkCertificate=false